config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :missions, only: %i[index show create] do
    resources :participations, only: %i[create]
  end

  get 'dashboard', to: 'pages#dashboard'
  get 'organisation_dashboard', to: 'pages#organisation_dashboard'

  resources :participations, only: [] do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :favorites, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :mission
  belongs_to :user

  validates :mission_id, uniqueness: { scope: :user_id }
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :organisation
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_one_attached :photo
  has_many :participations

  validates :title, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :address, presence: true

  CATEGORIES = [
    "Collecte et distribution",
    "Environnement et écologie",
    "Soutien scolaire",
    "Animation culturelle"
  ]

end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :missions
  has_one_attached :photo
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :mission

  validates :mission_id, uniqueness: { scope: :user_id, message: "Cette mission est déjà réservée" }
  STATUS = ["pending", "accepted", "rejected"]
  validates :status, presence: true, inclusion: { in: STATUS }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :participations, dependent: :destroy
  has_many :missions, through: :participations
  has_many :favorites, dependent: :destroy
  has_many :missions, through: :favorites
  has_many :organisations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def pending_missions
    participations.where(status: "pending").map(&:mission)
    # participations.where(status: "pending").map do |participation|
    #   participation.mission
    # end
  end

  def accepted_missions
    participations.where(status: "accepted").map(&:mission)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def default_url_options
    { host: ENV['DOMAIN'] || 'localhost:3000' }
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = Favorite.new
    @favorite.user = current_user
    @favorite.mission = Mission.find(params[:format].to_i)
    @favorite.save
  end

  def destroy
    @favorite = current_user.favorites.find(params[:id])
    @favorite.destroy
    redirect_to dashboard_path, notice: "Mission retiré de vos favoris"
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController

  def show
    @mission = Mission.find(params[:id])
    @organisation = @mission.organisation
  end

  def index
    #@missions = Mission.joins(favorites: :user).where.not(favorites: { user: current_user }).or(Mission.where.not(associated))
    @missions = Mission
    .left_joins(:favorites)
    .or(Mission.where.not(id: Favorite.where(user_id: current_user.id).select(:mission_id)))

    @missions = @missions.where(address: params[:address]) if params[:address].present?
    @missions = @missions.where(category: params[:category]) if params[:category].present?
    @missions = @missions.where(start_date: params[:start_date]) if params[:start_date].present?
  end

  def create
    @mission = Mission.new(mission_params)
    @mission.organisation = current_user.organisations.first

    if @mission.save
      redirect_to organisation_dashboard_path, notice: "Mission créée avec succès."
    else
      @missions = current_user.organisations.first.missions
      @participations_per_mission = @missions.map do |mission|
        mission.participations.where(status: "pending")
      end
      render "pages/organisation_dashboard", status: :unprocessable_entity
    end
  end

  private

  def mission_params
    params.require(:mission).permit(:title, :description, :category, :address, :start_date, :end_date, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  before_action :ensure_admin!, only: [:organisation_dashboard]

  def home
  end

  def dashboard
    @favorites = current_user.favorites
    @pending_missions = current_user.pending_missions
    @accepted_missions = current_user.accepted_missions
  end

  def organisation_dashboard
    @missions = current_user.organisations.first.missions
    @participations_per_mission = @missions.map do |mission|
      mission.participations.where(status: "pending")
    end
    @mission = Mission.new
  end

  private

  def ensure_admin!
    raise unless current_user.admin
    # render file: "#{Rails.root}/public/400.html", layout: false, status: :unauthorized unless current_user.admin
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  def create
    @mission = Mission.find(params[:mission_id])
    @participation = Participation.new
    @participation.mission = @mission
    @participation.user = current_user
    @participation.status = "pending"
    if Favorite.exists?(user: current_user, mission: @mission)
      favorite = current_user.favorites.find_by(mission: @mission)
      favorite.destroy
    # current_user.favorites.find_by(mission: @mission).destroy if current_user.favorites.exists?(mission: @mission)
    end
    if @participation.save
      redirect_to dashboard_path
    else
      # redirect "missions/show", status: :unprocessable_entity
      redirect_to mission_path(@mission), status: :unprocessable_entity

    end
  end

  def accept
    @participation = Participation.find(params[:id])
    @participation.update(status: "accepted")
    redirect_to organisation_dashboard_path, notice: "le participant #{@participation.user.username} est confirmé"
  end

  def reject
    @participation = Participation.find(params[:id])
    @participation.update(status: "rejected")
    redirect_to organisation_dashboard_path, notice: "le participant #{@participation.user.username} n'a pas été retenu"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
  content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
  content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
  meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image'])
  # petite astuce pour que cela fonctionne aussi bien avec un asset qu'avec une URL
  meta_image.starts_with?('http') ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BenevoFlex simplifie l’engagement bénévole en le rendant rapide, flexible et accessible. Trouvez en un clic une mission qui correspond à vos disponibilités grâce à notre système de matching intelligent. Un engagement sans contrainte pour maximiser l'impact associatif et encourager l’action !</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.typekit.net/jtv1qeu.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= favicon_link_tag %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!– Facebook Open Graph data –>
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!– Twitter Card data –>
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">


  </head>

  <body>
    <%= render "shared/navbar" %>
    <main>
      <%= render "shared/flashes" %>
      <%= yield %>
    </main>
     <%= render "shared/footer" %>
  </body>

</html>

app/views/missions/index.html.erb
    <div class="d-flex h-100">
      <div class="swipe-form">
        <%= form_with model: @mission, url: missions_path, method: :get, class: "d-flex flex-column py-3" do |form| %>

          <div class="" data-controller="form-expand">
            <%= form.label "Sélectionnez une adresse", class: "form-control select-field", data: {active: "false", action: "click->form-expand#expand"} %>
            <div class="search-dropdown" data-form-expand-target="selectField">
              <%= form.collection_radio_buttons :address, Mission.select(:address).distinct, :address, :address,
                  { },
                  { class: "d-none" }%>
            </div>
          </div>

          <div data-controller="form-expand" >
            <%= form.label "Sélectionnez une catégorie", class: "form-control select-field", data: {active: "false", action: "click->form-expand#expand"}  %>
            <div class="search-dropdown" data-form-expand-target="selectField">
              <%= form.collection_radio_buttons :category, Mission.select(:category).distinct, :category, :category,
                  { },
                  { class: "d-none"}%>
            </div>
          </div>

          <div >
            <%= form.text_field :start_date,
                class: "form-control select-field",
                data: {controller: "datepicker", action: "click->form-expand#expand blur->form-expand#collapse"},
                placeholder: "Sélectionnez une date" %>
          </div>

          <%= form.submit "Rechercher", class: "my-5 btn-form" %>
        <% end %>
      </div>

      <div class="central-elements">

        <div class="card-list-container d-flex position-relative ">
          <% @missions.each do |mission|%>
            <div class="d-flex align-items-center position-absolute gap-3" data-controller="swipe">
              <div class="pointer" data-action="click->swipe#dislike">
                <i class="fa-solid fa-circle-xmark picto"></i>
              </div>

              <div class="card" data-swipe-target="card">
                <% if mission.photo.attached? %>
                  <%= cl_image_tag mission.photo.key%>
                <% end %>
                <div class="card-infos">
                  <div>
                    <h1><%= mission.title  %></h1>
                    <p><%= mission.description %></p>
                  </div>
                </div>
              </div>

              <div >
                <%= link_to favorites_path(mission), data: {turbo_method: :post, action:"click->swipe#like"} do %>
                  <i class="fa-solid fa-heart picto"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="dashboard-button">
          <%= link_to "J'accède à ma sélection", dashboard_path, class:"btn my-3 btn-large"%>
        </div>
      </div>
    </div>

app/views/missions/show.html.erb
<div class="background">
 <div class="container">
     <div class="row justify-content-center">
      <div class="col-md-16">
        <%= cl_image_tag(@organisation.photo.key, class: "association-image", alt: @organisation.name, width: 1250, height: 350, crop: :fill, gravity: :auto) %>
      </div>
     </div>
 </div>
</div>

<div class="full-page-bg">
  <div class="second-section position-relative">
    <div class="container">
      <div class="row align-items-start">


 <div class="col-md-3 d-flex justify-content-center align-items-start">
    <%= cl_image_tag(@mission.photo.key, class: "mission-image-2", alt: @mission.title, width: 250, height: 250, crop: :fill, gravity: :auto) %>
  </div>


  <div class="col-md-9 d-flex flex-column align-items-start justify-content-start third-section">
     <h2 class="mb-2 text-center w-100 organisations-text">Association : <%= @organisation.name %></h2>
        <p class="mb-3 font-paragrah"><%= @organisation.description %></p>
      <h2 class="mb-2 text-center w-100 organisations-text">Mission : <%= @mission.title %></h2>
        <p class="mb-3 font-paragrah"><%= @mission.description %></p>

    <div class="mt-3 w-100 d-flex justify-content-between">
      <div class="col-md-3">
        <% if current_user.participations.exists?(mission_id: @mission.id, status: "accepted") %>
             <button class="btn fw-bold text-uppercase w-120" disabled>Déjà engagé</button>
         <% elsif current_user.participations.exists?(mission_id: @mission.id, status: "pending") %>
             <button class="btn fw-bold text-uppercase w-120" disabled>Demande envoyée</button>
       <% else %>
            <%= link_to "Je m'engage", mission_participations_path(@mission), data: { turbo_method: :post }, class: "btn fw-bold text-uppercase bg-black w-120" %>
       <% end %>
      </div>
      <div class="col-md-3 text-end">
        <%= link_to "Retour sur mon espace", dashboard_path(@mission), class: "btn fw-bold text-uppercase w-120" %>
      </div>
    </div>

  </div>
      </div>
 </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="dashboard-container">
  <div class="row justify-content-center w-100">

    <div class="col-md-4">
      <div class="selection-container">
        <h2 class="selection-title">Ma sélection</h2>
        <div class="missions-container d-flex flex-wrap justify-content-center">
            <% if @favorites.any? %>
            <% @favorites.each do |favorite| %>
              <div class="card mission-card mx-2 my-2 position-relative">
              <!-- Bouton destroy avec croix en haut à droite -->
              <%= link_to favorite_path(favorite), method: :delete, data: { turbo_method: :delete, confirm: "Supprimer ?" }, class: "delete-favorite-btn" do %>
                <i class="fa-solid fa-circle-xmark"></i>
              <% end %>

              <div class="mission-card-content">
                <% if favorite.mission.photo.attached? %>
                  <%= link_to mission_path(favorite.mission) do %>
                    <%= cl_image_tag(favorite.mission.photo.key, class: "mission-image") %>
                  <% end %>
                <% end %>
              </div>

              <div class="card-body">
                <h3 class="mission-title"><%= favorite.mission.title  %></h3>
              </div>
            </div>
              <%end%>
          <%else%>
            <p class="message-mission">Vous n'avez sélectionné aucune mission</p>
          <% end %>

        </div>
      </div>
    </div>


    <div class="col-md-4">
      <div class="selection-container-2">
        <h2 class="selection-title text-center">Missions en attente de validation</h2>
        <div class="missions-container d-flex flex-wrap justify-content-center">
          <%if @pending_missions.any? %>
          <% @pending_missions.each do |mission| %>
            <div class="card mission-card mx-2 my-2">
              <div class="mission-card-content">
                <% if mission.photo.attached? %>
                  <%= link_to mission_path(mission) do %>
                    <%= cl_image_tag(mission.photo.key, class: "mission-image") %>
                  <% end %>
                <% end %>
              </div>
              <div class="card-body">
                <h3 class="mission-title"><%= mission.title %></h3>
                <!--<p class="mission-description"><%= mission.description.truncate(80) %></p>-->
              </div>
            </div>
            <% end %>
          <%else%>
            <p class="message-mission">Vous n'avez aucune mission en attente de validation</p>
          <% end %>
        </div>
      </div>
    </div>


    <div class="col-md-4">
      <div class="selection-container-3">
        <h2 class="selection-title">Mes missions à venir</h2>
        <%= month_calendar(events: @accepted_missions, attribute: :start_date, end_attribute: :end_date) do |date, missions| %>
         <% missions.each do |mission| %>
            <%= link_to mission_path(mission), class: "event-day", title: mission.title do%>
            <% end %>
        </div>
        <% end %>
            <%= date.day %>
          <% end %>
        <% @accepted_missions.each do |mission| %>
          <div class="card mission-card mx-2 my-2">
            <% if mission.photo.attached? %>
              <%= link_to mission_path(mission) do %>
                <%= cl_image_tag(mission.photo.key, class: "mission-image") %>
              <% end %>
            <% end %>
            <div class="card-body">
              <h3 class="mission-title"><%= mission.title %></h3>
              <!--<p class="mission-description"><%= mission.description.truncate(80) %></p>-->
            </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="hero-container">
  <div class="separator"></div> <!-- Fond kaki -->
  <div class="hero-image">
    <%= image_tag 'Rectangle_4472_V2.jpg', class: 'img-fluid' %> <!-- L’image est indépendante du fond -->
  </div>
</div>

<div class="page-content"> <!-- Cette div va faire descendre le kaki -->
  <div class="container">
    <section class="intro">
      <p>
        Vous aimeriez donner de votre temps, mais vous ne savez pas où chercher ?<br>
        Vous avez peut-être 1h par semaine ou des compétences spécifiques à offrir ponctuellement,<br>
        mais aucune plateforme ne vous permet de vous engager facilement ?
      </p>
      <div class="intro-bis">
        <h2>VOUS ÊTES AU BON ENDROIT</h2>
      </div>
    </section>
  </div>

  <section class="features mx-0 row text-center">
    <div class="col-md-3 feature">
      <i class="fa fa-calendar"></i>
      <h3>Des missions adaptées à votre emploi du temps</h3>
    </div>

    <div class="col-md-3 feature">
      <i class="fa fa-hand-pointer"></i>
      <h3>Swipez & Postulez en un clic</h3>
    </div>

    <%# <div class="col-md-3 feature">
      <i class="fa fa-check-circle"></i>
      <h3>Engagez-vous selon vos compétences</h3>
    </div> %>

    <div class="col-md-3 feature">
      <i class="fa fa-users"></i>
      <h3>Un accès rapide aux associations</h3>
    </div>
  </section>

    <div class="text-center">
      <a href="<%= missions_path %>" class="btn-index">Par ici pour trouver votre mission</a>
    </div>


        <!-- Section Témoignages -->
    <section class="testimonials-section py-3">
      <div class="testimonials-container">
        <div class="testimonials-big-title">
          <h2>Ils se sont engagés !</h2>
        </div>

        <!-- Slider Swiper -->
        <div class="swiper" data-controller="carousel">
          <div class="swiper-wrapper">

            <!-- Slide 1 -->
            <div class="swiper-slide">
              <div class="testimonial-content">
                <%= image_tag asset_path('1melissa.jpg'), class: 'testimonial-image' %>
                <div class="testimonials-text">
                 <h3>Mélissa, 20 ans - Soutien aux sans-abri</h3>
                  <p>
                    "J’ai trouvé une mission où j’aide à distribuer des repas et discuter avec des personnes sans-abri.
                    Ça me permet de casser certaines idées reçues."
                  </p>
                </div>
              </div>
            </div>

            <!-- Slide 2 -->
            <div class="swiper-slide">
              <div class="testimonial-content">
                <%= image_tag asset_path('1emma.jpg'), class: 'testimonial-image' %>
                <div class="testimonials-text">
                  <h3>Emma, 21 ans - Aide aux devoirs</h3>
                  <p>
                    "Entre les cours et les exams, ce n'était pas évident de donner de mon temps.
                    BenevoFlex m’a permis de trouver une association pour aider des collégiens en maths,
                    quand je veux !"
                  </p>
                </div>
              </div>
            </div>

            <!-- Slide 3 -->
            <div class="swiper-slide">
              <div class="testimonial-content">
                <%= image_tag asset_path('1lucas.jpg'), class: 'testimonial-image' %>
                <div class="testimonials-text">
                  <h3>Lucas, 23 ans - Protection de l’environnement</h3>
                  <p>
                    "Je voulais agir concrètement pour l’écologie. Grâce à BenevoFlex,
                    j’ai participé à des nettoyages de plages et rencontré des gens inspirants.
                    Je me sens vraiment utile !"
                  </p>
                </div>
              </div>
            </div>

            <!-- Slide 4 -->
            <div class="swiper-slide">
              <div class="testimonial-content">
                 <%= image_tag asset_path('1lena.jpg'), class: 'testimonial-image' %>
                <div class="testimonials-text">
                   <h3>Léna, 36 ans - Protection animale</h3>
                  <p>
                    "Je voulais aider, mais je ne savais pas où chercher...
                    Sur BenevoFlex, j’ai filtré par mes centres d’intérêt
                    et j’ai trouvé une association qui sauve des animaux.
                    Je peux les aider quand j’ai du temps libre. Trop facile !"
                  </p>
                </div>
              </div>
            </div>

            <!-- Slide 5 -->
            <div class="swiper-slide">
              <div class="testimonial-content">
                <%= image_tag asset_path('1jules.jpg'), class: 'testimonial-image' %>
                <div class="testimonials-text">
                  <h3>Jules, 22 ans - Animation en maison de retraite</h3>
                  <p>
                    "J’adore échanger avec les personnes âgées. Sur BenevoFlex,
                    j’ai découvert qu’une maison de retraite cherchait des étudiants
                    pour animer des jeux et discuter avec les résidents.
                    Ça me fait du bien autant qu’à eux !"
                  </p>
                </div>
              </div>
            </div>

          </div>

          <!-- Pagination -->
          <div class="swiper-pagination"></div>

          <!-- Navigation -->
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>
        </div>
      </div>
    </section>
  </div>
</div>
  <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
/>

<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

app/views/pages/organisation_dashboard.html.erb
<!-- Section 1 : Participations en attente -->
<body class="dashboard-page">

  <div class="dashboard-container-orga">
      <div class="row justify-content-start w-100">
      <div class="col-md-4">
        <div class="selection-container-orga">
          <h2 class="selection-title">Mes participations en attente de validation</h2>


          <div class="missions-container d-flex flex-wrap justify-content-center">
            <% @participations_per_mission.each do |participations| %>
                <% next if participations.empty? %> <!-- si pas de participation on passe a la mission suivante  -->
                <div class="mission-mini-card-orga  mx-2 my-2 position-relative">
                  <h3 class="mission-title-orga"><%= participations.first.mission.title %></h3>
                  <div class="mission-mini-card-orga mx-2 my-2 position-relative d-flex flex-column justify-content-between">
                    <ul>
                      <!-- section accept / refuse participation  -->
                      <% participations.each do |participation| %>
                        <li class="participation-line-mission text-center">
                        <div class="content-block">
                          <div class="participant-info d-flex flex-column align-items-center mb-2">
                            <div class="d-flex flex-column align-items-center gap-1">
                              <%if participation.user.photo_url?%>
                              <%= image_tag(participation.user.photo_url) %>
                              <span class="participant-name"><%= participation.user.username %></span>
                              <% end %>
                            </div>
                            </div>

                          <!-- accept participation  -->
                          <div class="action-buttons-orga d-flex justify-content-center gap-3 mb-2  mt-auto">
                          <%= button_to accept_participation_path(participation), method: :patch, class: "btn btn-success" do %>
                            <i class="fas fa-check-circle"></i>
                          <% end %>

                          <!-- reject participation  -->
                          <%= button_to reject_participation_path(participation), method: :patch, class: "btn btn-danger" do %>
                            <i class="fas fa-times-circle"></i>
                          <% end %>
                        </div>
                      <% end %>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>

        </div>
      </div>



      <!-- Section 2 : Mes misions mis à disposition -->
      <div class="col-md-4">
        <div class="selection-container-orga">
          <h2 class="selection-title">Mes missions mises à disposition</h2>
          <div class="missions-container d-flex flex-wrap justify-content-center">
            <% @missions.each do |mission| %>
              <div class="card mission-card mx-2 my-2 position-relative">
                <% if mission.photo.attached? %>
                  <%= link_to cl_image_tag(mission.photo.key, class: "mission-image"), mission_path(mission) %>
                <% end %>

                <div class="card-body">
                  <h3 class="mission-title"><%= mission.title %></h3>
                  <!--<p class="mission-description"><%= mission.description %></p> -->
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>


      <!-- Section 3 : Formulaire pour créer une mission -->
      <section class="col-md-4">
        <%= simple_form_for @mission, url: missions_path, html: { multipart: true, class: 'mission-form' } do |f| %>
        <h2 class="section-title">Créer une nouvelle mission</h2>
          <div class="form-group">
            <%= f.input :title, label: "Titre de la mission", class: 'form-input' %>
          </div>

          <div class="form-group">
            <%= f.input :description, label: "Description", class: 'form-input' %>
          </div>

          <div class="form-group">
            <%= f.input :category, collection: Mission::CATEGORIES, prompt: "Sélectionnez une catégorie", label: "Catégorie", class: 'form-control form-input' %>
          </div>

          <div class="form-group">
            <%= f.input :address, label: "Adresse / Lieu", class: 'form-input' %>
          </div>

          <div class="form-group">
            <%= f.input :start_date,  as: :string,
              input_html: { data: { controller: "datepicker" } }, label: "Date de début", class: 'form-control form-input' %>
          </div>

          <div class="form-group">
            <%= f.input :end_date, as: :string,
              input_html: { data: { controller: "datepicker" } }, label: "Date de fin", class: 'form-input' %>
          </div>

          <div class="form-group">
            <%= f.input :photo, as: :file, label: "Image de la mission", class: ' form-input' %>
          </div>

          <div class="form-group">
            <%= f.button :submit, "Créer la mission", class: 'form-button-mission' %>
          </div>
        <% end %>
      </section>

      </div>
  </div>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-hands-holding-circle"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Toutes les missions", missions_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.photo_url, class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon espace", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Espace associations", organisation_dashboard_path, class: "dropdown-item" %>
              <%= link_to "Quitter ma session", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Accéder à mon espace", dashboard_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>